name: jamt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  entities:
    path: packages/entities
  domain:
    path: packages/domain
  data:
    path: packages/data
  app_localization:
      path: packages/app_localization
  bloc: ^9.0.0
  equatable: ^2.0.0
  flutter_bloc: ^9.1.0
  formz: ^0.8.0
  qr_code_scanner_plus: ^2.0.10+1
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  lottie: ^3.3.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0

dev_dependencies:
  bloc_test: ^10.0.0
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  test: ^1.25.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login_background2.webp
    - assets/images/main_logo_white.png
    - assets/images/main_logo_apce_5.webp
    - assets/images/main-logo-azul.png
    - assets/images/main_drawer_background.png
    - assets/images/home_activity_1.webp
    - assets/images/home_activity_2.webp
    - assets/images/home_activity_3.webp
    - assets/images/home_activity_4.webp
    - assets/images/home_activity_5.webp
    - assets/images/home_activity_6.webp
    - assets/images/home_activity_7.webp
    - assets/images/home_activity_8.webp
    - assets/images/home_activity_9.webp
    - assets/images/home_activity_10.webp
    - assets/images/home_activity_11.webp
    - assets/images/home_activity_12.webp
    - assets/images/home_activity_13.webp
    - assets/images/home_activity_14.webp
    - assets/images/home_guests.webp
    - assets/images/home_bulletin.webp
    - assets/images/home_workshops.webp
    - assets/images/home_sessions.jpg
    - assets/images/home_tourism.jpg
    - assets/images/home_stands.webp
    - assets/images/home_qr.webp
    - assets/images/home_main_objectives.webp
    - assets/images/activity_card_a1.jpg
    - assets/images/activity_card_a2.png
    - assets/images/activity_card_a3.jpg
    - assets/images/activity_card_a4.jpg
    - assets/images/activity_card_a5.jpg
    - assets/images/activity_image_2.webp
    - assets/images/guest_card_1.webp
    - assets/images/logo_worship.png
    - assets/images/logo_mrnt.webp
    - assets/images/activity_image_1.webp
    - assets/images/guide_card_1.webp
    - assets/images/guests_1.webp
    - assets/images/guests_2.webp
    - assets/images/guests_3.webp
    - assets/images/guests_4.webp
    - assets/images/guests_5.webp
    - assets/images/guests_6.webp
    - assets/images/guests_7.webp
    - assets/images/guests_8.webp
    - assets/images/guests_9.webp
    - assets/images/guests_10.webp
    - assets/images/guests_11.webp
    - assets/images/guests_12.webp
    - assets/images/guests_13.webp
    - assets/images/guests_14.webp
    - assets/images/bulletin_1.webp
    - assets/images/maps/map_3_thumbnail.webp
    - assets/images/maps/map_3.webp
    - assets/lottie/check.json
    - assets/lottie/check_2.json
    - assets/lottie/check_3.json
    - assets/lottie/info.json
    - assets/lottie/lock.json
    - assets/lottie/qr_scan.json
    - assets/lottie/check_out.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Home
      fonts:
        - asset: assets/fonts/icon_home/Home.ttf
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
    - family: MuseoSans
      fonts:
        - asset: assets/fonts/museo-sans/MuseoSans-100.otf
          weight: 100
          style: normal
        - asset: assets/fonts/museo-sans/MuseoSans-100Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/museo-sans/MuseoSans-300.otf
          weight: 300
          style: normal
        - asset: assets/fonts/museo-sans/MuseoSans-300Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/museo-sans/MuseoSans-500.otf
          weight: 500
          style: normal
        - asset: assets/fonts/museo-sans/MuseoSans-500Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/museo-sans/MuseoSans-700.otf
          weight: 700
          style: normal
        - asset: assets/fonts/museo-sans/MuseoSans-700Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/museo-sans/MuseoSans-900.otf
          weight: 900
          style: normal
        - asset: assets/fonts/museo-sans/MuseoSans-900Italic.otf
          weight: 900
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
