// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0O-2hYjIBpgD_ud7qvOgiJ_dcRdC1XjU',
    appId: '1:212920800593:web:429b2184e0866f6901ef70',
    messagingSenderId: '212920800593',
    projectId: 'jamt-efcb2',
    authDomain: 'jamt-efcb2.firebaseapp.com',
    storageBucket: 'jamt-efcb2.firebasestorage.app',
    measurementId: 'G-6NLMQX335M',
    databaseURL: "https://jamt-efcb2-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCViF8_UE6uwAq7repjVwIDx_8me2s4tXc',
    appId: '1:212920800593:android:02eb4a46fa0c2c8201ef70',
    messagingSenderId: '212920800593',
    projectId: 'jamt-efcb2',
    storageBucket: 'jamt-efcb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxju5leIaFdF24dekJR9cf26LUI6iEC6U',
    appId: '1:212920800593:ios:7301af5b7e00261701ef70',
    messagingSenderId: '212920800593',
    projectId: 'jamt-efcb2',
    storageBucket: 'jamt-efcb2.firebasestorage.app',
    iosBundleId: 'pe.com.ja.mt.jamt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxju5leIaFdF24dekJR9cf26LUI6iEC6U',
    appId: '1:212920800593:ios:7301af5b7e00261701ef70',
    messagingSenderId: '212920800593',
    projectId: 'jamt-efcb2',
    storageBucket: 'jamt-efcb2.firebasestorage.app',
    iosBundleId: 'pe.com.ja.mt.jamt',
  );
}
